# 自定义规则模板
# 包含敏感域名和IP的规则配置

# 高性能代理规则
high_performance_domains:
  - DOMAIN-SUFFIX,openrouter.ai,⚡HIGH-PERFORMANCE
  - DOMAIN-SUFFIX,${PRIVATE_DOMAIN_1},⚡HIGH-PERFORMANCE
  - DOMAIN-SUFFIX,api.ephone.ai,⚡HIGH-PERFORMANCE
  - DOMAIN-SUFFIX,lb.${PRIVATE_DOMAIN_1},⚡HIGH-PERFORMANCE
  - DOMAIN-SUFFIX,generativelanguage.googleapis.com,⚡HIGH-PERFORMANCE

# 直连域名规则
direct_domains:
  - DOMAIN-SUFFIX,${PRIVATE_DOMAIN_2},DIRECT
  - DOMAIN-SUFFIX,${PRIVATE_DOMAIN_3},DIRECT
  - DOMAIN-SUFFIX,${PRIVATE_DOMAIN_4},DIRECT
  - DOMAIN-SUFFIX,${PRIVATE_DOMAIN_5},DIRECT

# 直连IP规则
direct_ips:
  - IP-CIDR,${PRIVATE_IP_RANGE_1},DIRECT
  - IP-CIDR,${PRIVATE_IP_RANGE_2},DIRECT

# 特定服务规则
service_domains:
  - IP-CIDR,${SERVICE_IP_1}/32,DIRECT
  - DOMAIN-SUFFIX,${SERVICE_DOMAIN_1},DIRECT
  - DOMAIN-SUFFIX,${SERVICE_DOMAIN_2},DIRECT
  - DOMAIN-SUFFIX,${SERVICE_DOMAIN_3},📀NETFLIX
  - IP-CIDR,${SERVICE_IP_2}/32,DIRECT

# 地区服务规则
region_services:
  - DOMAIN-SUFFIX,${REGION_DOMAIN_1},DIRECT
  - DOMAIN-SUFFIX,${REGION_DOMAIN_2},DIRECT
  - IP-CIDR,${REGION_IP_1}/32,DIRECT

# 香港相关规则
hk_rules:
  - IP-CIDR,${HK_IP_1}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_2}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_3}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_4}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_5}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_6}/32,1.🇭🇰HK
  - DOMAIN-SUFFIX,${HK_DOMAIN_1},1.🇭🇰HK
  - DOMAIN-SUFFIX,${HK_DOMAIN_2},1.🇭🇰HK
  - IP-CIDR,${HK_IP_7}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_8}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_9}/32,1.🇭🇰HK
  - IP-CIDR,${HK_IP_10}/32,1.🇭🇰HK
  - DOMAIN-SUFFIX,${HK_IP_11},1.🇭🇰HK
  - IP-CIDR,${HK_IP_RANGE_1}/24,1.🇭🇰HK
  - IP-CIDR,${HK_IP_RANGE_2}/24,1.🇭🇰HK

# 内部网络规则
internal_networks:
  - IP-CIDR,${INTERNAL_IP_1}/24,DIRECT
  - IP-CIDR,${INTERNAL_IP_2}/24,DIRECT
  - IP-CIDR,${INTERNAL_IP_3}/24,DIRECT
  - IP-CIDR,${INTERNAL_IP_4}/24,DIRECT

# 特殊域名规则
special_domains:
  - DOMAIN-SUFFIX,${SPECIAL_DOMAIN_1},DIRECT
  - DOMAIN-SUFFIX,${SPECIAL_DOMAIN_2},DIRECT
  - DOMAIN-SUFFIX,${SPECIAL_DOMAIN_3},DIRECT